//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionServiceAdaptor.EmailGatewayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailGatewayService.IEmailGateway")]
    internal interface IEmailGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailGateway/SendText", ReplyAction="http://tempuri.org/IEmailGateway/SendTextResponse")]
        bool SendText(string mailFrom, string mailTo, string bcc, string cc, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailGateway/SendHtml", ReplyAction="http://tempuri.org/IEmailGateway/SendHtmlResponse")]
        bool SendHtml(string mailFrom, string mailTo, string bcc, string cc, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailGateway/SendTextAttachments", ReplyAction="http://tempuri.org/IEmailGateway/SendTextAttachmentsResponse")]
        bool SendTextAttachments(string mailFrom, string mailTo, string bcc, string cc, string subject, string body, System.Collections.Generic.Dictionary<string, string> fileNameAttachmentContents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailGateway/SendHtmlAttachments", ReplyAction="http://tempuri.org/IEmailGateway/SendHtmlAttachmentsResponse")]
        bool SendHtmlAttachments(string mailFrom, string mailTo, string bcc, string cc, string subject, string body, System.Collections.Generic.Dictionary<string, string> fileNameAttachmentContents);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IEmailGatewayChannel : TransactionServiceAdaptor.EmailGatewayService.IEmailGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class EmailGatewayClient : System.ServiceModel.ClientBase<TransactionServiceAdaptor.EmailGatewayService.IEmailGateway>, TransactionServiceAdaptor.EmailGatewayService.IEmailGateway {
        
        public EmailGatewayClient() {
        }
        
        public EmailGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendText(string mailFrom, string mailTo, string bcc, string cc, string subject, string body) {
            return base.Channel.SendText(mailFrom, mailTo, bcc, cc, subject, body);
        }
        
        public bool SendHtml(string mailFrom, string mailTo, string bcc, string cc, string subject, string body) {
            return base.Channel.SendHtml(mailFrom, mailTo, bcc, cc, subject, body);
        }
        
        public bool SendTextAttachments(string mailFrom, string mailTo, string bcc, string cc, string subject, string body, System.Collections.Generic.Dictionary<string, string> fileNameAttachmentContents) {
            return base.Channel.SendTextAttachments(mailFrom, mailTo, bcc, cc, subject, body, fileNameAttachmentContents);
        }
        
        public bool SendHtmlAttachments(string mailFrom, string mailTo, string bcc, string cc, string subject, string body, System.Collections.Generic.Dictionary<string, string> fileNameAttachmentContents) {
            return base.Channel.SendHtmlAttachments(mailFrom, mailTo, bcc, cc, subject, body, fileNameAttachmentContents);
        }
    }
}
